# Codecov Configuration
# Reference: https://docs.codecov.com/docs/codecovyml-reference

flags:
    e2e:
        carryforward: true # Preserve coverage data across uploads to avoid losing history
        paths:
            - 'assets/src/'

coverage:
    status:
        project:
            default:
                target: auto
                threshold: 5%
                if_ci_failed: ignore

        patch:
            default:
                target: auto
                threshold: 5%
                if_ci_failed: ignore

        changes:
            default:
                target: auto
                threshold: 5%
                if_ci_failed: ignore

ignore:
    - '*.min.css'
    - '*.min.js'
    - '.wp-env'
    - 'build'
    - 'dist'
    - 'docs'
    - 'node_modules'
    - 'tests'
    - 'vendor'
