name: Code Standards
on:
  pull_request:

jobs:
  phpcs:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Required for phpcs-changed to compare with base branch
        
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        tools: composer:v2
        
    - name: Install Dependencies
      run: composer install
        
    - name: Run PHPCS on changed files
      run: |
        CHANGED_FILES=$(git diff --name-only --diff-filter=d origin/${{ github.base_ref }} | grep ".php$" || true)
        if [ ! -z "$CHANGED_FILES" ]; then
          vendor/bin/phpcs-changed \
            --git-base=origin/${{ github.base_ref }} \
            --phpcs-path=vendor/bin/phpcs \
            --standard=.phpcs.xml.dist \
            $CHANGED_FILES
        else
          echo "No PHP files changed"
        fi